### PR TITLE
Add rkglChainLinkSelect()

### PR DESCRIPTION
**Pull request by kdaic**
Added a function similar to rkglFrameHandleSelect() into rkglChain API.  
With this addition, updating sample example/chain/select_test.c.  
Please check it.

### CODE REVIEW

**Comment by zhidao** [comment]
I ask you again not to modify the library code but suggest your new function(s) in your example code.
rkglChainLinkSelect() seems convenient.

**Comment by kdaic** [comment]
@zhidao  
I moved a new function rkglChainLinkSelect() from library code rkgl_chain.h(,c) into sample select_test.c for suggesction.
Please see it & concern whether to add it into the library.

**Comment by zhidao** [comment]
I'm sorry, but I found that it is not preferable to merge your rkglChainLinkSelect() into the library.
A typical process of object selection and manipulation is something like the following.
 1. Click a canvas.
 2. Check if there is something at the clicked point by using rkglSelectionFindNearest().
 3. Figure out what is selected by using rkglSelectionName().
 4. Apply a defined manipulation to the selected object.
Though your rkglChainLinkSelect() does the above process from 1 to 3, something else might be selected in general. Actually, the rkglChainLinkSelect() is not available for select_multi_test.c. It means that the function is not a general operation but rather application-specific.

**Comment by kdaic** [comment]
Hmm.. I agree.  
But I feel like the same thing can be said for FrameHandle.  
How does FrameHandleSelect()  handle this?

**Comment by zhidao** [comment]
True. An idea is to exclude rkglSelectionFindNearest() from rkglFrameHandleSelect(). Probably, it makes the situation straightened.

A difference from rkglChainLinkSelect() is that rkglFrameHandle is basically expected to have a unique instance in an application, and rkglFrameHandleSelect() checks if the handle is selected or not. On the other hand, applications might have multiple instances of rkglChain just as shown in select_multi_test.c. In such a case, it is not sufficient to find a link but needs to find a combination of a link and a chain. Since the selection buffer manages objects only by numbers, I think it is hard to pick up both a link and a chain inside of rkglChainLinkSelect().

**Comment by kdaic** [comment]
Hmm... 
Sorry for the confirmation, 
but In other words, when there are multiple chains (like select_multi_test.c) if I want to use something like rkglChainLinkSelect(), do I need to assign a unique number to each chain ?  
However, there are clearly two problems, and that's what you're talking about, right ?   
1) Is it possible to assign a unique number ?  
2) Is it possible to manage the number chain ?  
The problem is that these things depend on the application situation and are not necessarily guaranteed, right?

**Comment by zhidao** [comment]
You are right. As you recognize, how to manage objects by names is application programmers' responsibility. And, it is the reason why I hesitate to include rkglChainLinkSelect() (and something like rkglChainLink()) to the library.

**Comment by kdaic** [comment]
Hmm.. OK. I understood.  
I try to write a function like rkglChainLinkSelect() on the application side.  
(It may be used a lot of similar code, and It may become a long and redundant line..)   
It's okay to close this PR.

**Comment by zhidao** [comment]
I added `rkglChainLinkFindSelected()` in the latest version of main branch, which is almost identical with your `rkChainLinkSelect()`. An example is found in example/chain/select_multi_test.c in addition to example/chain/select_test.c.

**Comment by zhidao** [comment]
@kdaic Is it OK for you to close this PR?

**Pull request closed without merging**
